import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const outfit = Outfit({
	subsets: ["latin"],
	variable: "--font-outfit",
	weight: ["400", "500", "600", "700"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
